mysql:
    host: 34.29.130.158
    port: 3334
    user: ngqbR2N4miKvHuXoQydmodlfYmjjOl1xLCvCJxwc+Y4=
    password: /VIzexSn6/wHiguCOVUOTqFS+zcCwsNMygGU7xHY2YM=
    database: stock_db

origin:
    frontend: http://localhost:3000