mysql:
#    host: 34.29.130.158
    host: 180.188.226.161
    port: 3334
    user: ngqbR2N4miKvHuXoQydmodlfYmjjOl1xLCvCJxwc+Y4=
    password: /VIzexSn6/wHiguCOVUOTqFS+zcCwsNMygGU7xHY2YM=
    database: stock_db

origin:
    frontend: http://localhost:3000

qdrant:
    url: http://180.188.226.161:6333
    collection_prefix: yt_collection_

llama:
    embedding_model: sentence-transformers/all-MiniLM-L6-v2
    llama_model: llama3.2:1b